language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make
  - make test
  - make gcov
branches:
  only:
    - master
after_success:
  - codecov -t c6180706-1b18-4fe4-8197-532cca9cc176 -X gcov
